title: Webex Contact Center Lab Repository
description: © 2022 Webex CC Lab repository, All right reserved.
author:
  name: Lab Support Email
  email: 'wxcclabs@cisco.com'
remote_theme: jekyll/minima

minima:
  skin: dark

  
